#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-XBase
version:      0.233
version_from: lib/DBD/XBase.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
